# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXe-QyyZGzKNxKaKSr5f2uRNjOI380IZ
"""

# Commented out IPython magic to ensure Python compatibility.
# from fastapi import FastAPI
# import nest_asyncio
# import uvicorn
# from pyngrok import ngrok
# from preprocessing import clean_text
# from generation import generer_reponse
# app = FastAPI()
# @app.get("/")
# def home():
#     return {"message": "API Avis Clients OK"}
# @app.post("/analyse")
# def analyser_avis(texte: str):
#     texte_clean = clean_text(texte)
#     reponse = generer_reponse(texte_clean)
#     return {
#         "texte": texte_clean,
#         "reponse": reponse
#     }
# if __name__ == "__main__":
#     nest_asyncio.apply()
#     public_url = ngrok.connect(8000)
#     print("URL publique :", public_url)
#     uvicorn.run(app, port=8000)
