# -*- coding: utf-8 -*-
"""batch_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1yqhUZRWMvQRuLpOldTqWbYW_f4y1qd
"""

# Commented out IPython magic to ensure Python compatibility.

# import pandas as pd
# from preprocessing import load_reviews
# from generation import generer_reponse
 
# df = load_reviews(limit=100000)
# df_negatifs = df[df["label"] == 2].copy()
# df_test = df_negatifs.head(25)
 
# reponses = []
# batch_size = 5
 
# for i in range(0, len(df_test), batch_size):
#     batch = df_test["texte_clean"].iloc[i:i+batch_size]
#     for texte in batch:
#         reponses.append(generer_reponse(texte))
#     print(f"Batch {i//batch_size + 1} terminé")
 
# df_test["reponse"] = reponses
# print(df_test[["texte_clean", "reponse"]])
