import pandas as pd
import re
from datasets import load_dataset
# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2CkP-IyCQ_kyjfLwaHXF7qITMnG6BXW
"""

# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2CkP-IyCQ_kyjfLwaHXF7qITMnG6BXW
"""

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-zàâéèêëîïôùûç0-9\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def label_sentiment(label):
    if label == 1:
        return "positive"
    elif label == 2:
        return "negative"
    return "neutral"

def load_reviews(limit=1000):
    dataset = load_dataset(
        "SetFit/amazon_reviews_multi_fr",
        split=f"train[:{limit}]"
    )
    df = pd.DataFrame(dataset)
    df["texte_clean"] = df["text"].apply(clean_text)
    df["sentiment"] = df["label"].apply(label_sentiment)
    return df
    
