# -*- coding: utf-8 -*-
"""tests/test_dummy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtY38RuDgMye6A5h9wW16OFInqt_4E-n
"""

# tests/test_dummy.py
def test_placeholder():
    assert True